Added fixture setup_ups to set up UPS in test environment
marcmengel/jobsub_lite pull request #104
Opened 2022-08-31 17:17 UTC by shreyb

This PR just adds a fixture to the `test_packages_unit` tests that sets up UPS, in case it's not already set up in the user's environment.  In a standard terminal/shell, a developer can just set up UPS/Spack, and then run the pytest command manually; but in an IDE like VSCode, PyCharm, etc., the environment for the native IDE testing functionality is often separate from the built-in terminal, and so simply sourcing a script won't work.  This change should ensure that no matter where a developer is running the tests from, as long as UPS is available, the unit tests should behave as expected.

2022-08-31 17:36 UTC, shreyb commented
Notes:
1.  I verified that with this change, all unit tests now pass
2. Requested @marcmengel as reviewer because he wrote the original unit tests, and is the most familiar with the various package managers we use like UPS and Spack.

2022-09-02 00:53 UTC, marcmengel requested changes
Looks good overall, should also try /grid/fermiapp/products/common/etc/setups.sh, in case
we have /grid/fermiapp mounted but not /cvmfs (i.e. fifeutilgpvm01) .
maybe check which one exists in setup_ups.

2022-09-02 03:55 UTC, shreyb commented
Good point, Marc.  I added in a check for the ups setup script in /grid/fermiapp if CVMFS fails.  Please let me know if this is OK and if there are any other issues you see with the PR.

2022-09-06 15:10 UTC, shreyb commented
@marcmengel does this look good now?

2022-09-07 14:51 UTC, merged