sigh... turning weakened tokens back off
marcmengel/jobsub_lite pull request #209
Opened 2023-01-11 17:58 UTC by marcmengel

until we figure out authentication issue for production/POMS submisssion (kcron?)

2023-01-11 19:34 UTC, shreyb requested changes
This looks good, but would it be possible to comment out the code in jobsub_submit that looks at token_mods.py, and/or put a note in there that it currently doesn't do anything, but is there for a future implemented feature?

2023-01-12 15:19 UTC, marcmengel commented
Well if we comment out the calls, we won't have token_scope defined, and we'll have to actually remove the lines from the templates rather than comment them out...

2023-01-12 15:26 UTC, shreyb commented
Got it. Then it's fine as is. Feel free to merge this - I'm away from a computer for the next few hours.

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
From: Marc Mengel ***@***.***>
Sent: Thursday, January 12, 2023, 9:20 AM
To: marcmengel/jobsub_lite ***@***.***>
Cc: Shreyas Bhat ***@***.***>; Review requested ***@***.***>
Subject: Re: [marcmengel/jobsub_lite] sigh... turning weakened tokens back off  (PR #209)


Well if we comment out the calls, we won't have token_scope defined, and we'll have to actually remove the lines from the templates rather than comment them out...

—
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_marcmengel_jobsub-5Flite_pull_209-23issuecomment-2D1380552090&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=9KiqjvYREicTD__c-Knj2w&m=AohgwJSwGPsFSbwZKIoZBo6kol5pXQayYZuaVU-EmZjLnrZHgnEtKL2aQVSxRXvu&s=bEyvMssg-jHt-A7o99a7__xdRIuRMBkiOGLG-QlOfCQ&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AEWIQ36VAWCMF4U7G2MYBTLWSAOJ5ANCNFSM6AAAAAATYKJGGA&d=DwMCaQ&c=gRgGjJ3BkIsb5y6s49QqsA&r=9KiqjvYREicTD__c-Knj2w&m=AohgwJSwGPsFSbwZKIoZBo6kol5pXQayYZuaVU-EmZjLnrZHgnEtKL2aQVSxRXvu&s=3-F929HyDEJMpmVN9da7C_4gGwxfmp5fSutTa6VROI4&e=>.
You are receiving this because your review was requested.Message ID: ***@***.***>

2023-01-12 19:45 UTC, shreyb approved these changes

2023-01-12 19:48 UTC, merged