Updated --tar-file-name documentation with corrected behavior
marcmengel/jobsub_lite pull request #225
Opened 2023-01-18 20:03 UTC by shreyb

Documentation for change in #223, #224.

2023-01-18 21:00 UTC, marcmengel requested changes
At the moment, the later --tar_file_name options will set
INPUT_TAR_FILE_{1,2,3...}
but
INPUT_TAR_DIR_LOCAL{1.2.3}
(no underscore).   We should either add the underscores in the simple.sh template,
 or take them out here. (probably the former, look for "INPUT_TAR_DIR_LOCAL{{loop.index0}}" and add the underscore.).

2023-01-18 21:43 UTC, shreyb commented
Yeah - I'd opt for adding the underscore as well.  I'll put that in.

2023-01-18 21:48 UTC, shreyb commented
Changed.  Does this look good now, @marcmengel?

2023-01-19 14:30 UTC, marcmengel approved these changes

2023-01-19 14:31 UTC, merged