Make pylint happy
marcmengel/jobsub_lite pull request #77
Opened 2022-08-02 19:49 UTC by marcmengel

- Open calls done with "with" and encoding=
- f-strings instead of %s stuff throughout
- misc ... return ... else: reworks
- some things flagged out  with #pylint: comments
- long strings broken down all over.

2022-08-02 22:09 UTC, shreyb requested changes
Just a couple of small concerns. I just want to make sure some of the huge changes have been tested. If so, this is good to merge.

2022-08-03 20:59 UTC, shreyb commented on lib/dagnabbit.py
> -    df = open(values["dag"], "r")
Just a follow up - for both this and the comment in `condor_submit`, if you know that the pylint changes don't change the behavior, please consider these comments "resolved".

2022-08-04 21:10 UTC, marcmengel commented on bin/condor_submit_dag
> +    # schedd_name = schedd_add.eval("Machine")
Sure, we could.  pylint says we don't use schedd_name anywhere...

2022-08-04 21:12 UTC, marcmengel commented on bin/condor_submit_dag
> +    # schedd_name = schedd_add.eval("Machine")
Although part of me wants to leave it as an example of using the add to find out stuff...

2022-08-04 21:35 UTC, marcmengel commented on bin/condor_submit_dag
> +    # schedd_name = schedd_add.eval("Machine")
deleted.

2022-08-04 21:37 UTC, marcmengel commented
Just commenting that all the unit tests pass with these changes.

2022-08-04 21:37 UTC, merged